experiment_name: demo-mt
seed: 42
model_name: Helsinki-NLP/opus-mt-en-de
source_lang: en
target_lang: de
max_source_length: 256
max_target_length: 256

hf_dataset:
  path: wmt14
  name: de-en
  split_train: train
  split_eval: test
  text_column: translation

training:
  output_dir: outputs/demo-mt
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 1
  learning_rate: 5e-5
  weight_decay: 0.0
  num_train_epochs: 1
  warmup_ratio: 0.03
  logging_steps: 50
  eval_strategy: steps
  eval_steps: 200
  save_steps: 200
  save_total_limit: 2
  fp16: false
